site_name: OpenFlight Knowledgebase
repo_url: https://github.com/openflighthpc/mkdocs-test
nav:
  - Overview: 
    - index.md
    - Prerequisites: overview/prerequisites.md
    - Where Can I Get Help: overview/get-help.md
  - HPC Concepts:
    - hpc-concepts/index.md
    - Network and Hardware: hpc-concepts/network-hardware.md
    - Infrastructure: hpc-concepts/infrastructure.md
    - Base System: hpc-concepts/base-system.md
    - User Management: hpc-concepts/user-management.md
    - Storage: hpc-concepts/storage.md
    - Monitoring: hpc-concepts/monitoring.md
    - HPC Environment: hpc-concepts/hpc-environment.md
    - Verification: hpc-concepts/verification.md
  - HPC Environment Basics:
    - hpc-environment-basics/index.md
    - Linux Environment Usage:
      - hpc-environment-basics/linux-usage/index.md
      - CLI Basics:
        - hpc-environment-basics/linux-usage/cli-basics/index.md
        - Logging In: hpc-environment-basics/linux-usage/cli-basics/logging-in.md
        - Understanding the CLI: hpc-environment-basics/linux-usage/cli-basics/understanding-the-cli.md
        - Moving Between Hosts: hpc-environment-basics/linux-usage/cli-basics/moving-between-hosts.md
        - Becoming the Root User: hpc-environment-basics/linux-usage/cli-basics/becoming-root.md
      - Working with Data and Files: 
        - hpc-environment-basics/linux-usage/working-with-data/index.md
        - Storage Types: hpc-environment-basics/linux-usage/working-with-data/storage-types.md
        - Your Home Directory: hpc-environment-basics/linux-usage/working-with-data/your-home-directory.md
        - Copying Data Between Hosts: hpc-environment-basics/linux-usage/working-with-data/copy-between-hosts.md
        - Copying Data to a HPC Environment:
          - hpc-environment-basics/linux-usage/working-with-data/copying-data/index.md
          - Using CLI: hpc-environment-basics/linux-usage/working-with-data/copying-data/using-cli.md
          - Using Graphical Client: hpc-environment-basics/linux-usage/working-with-data/copying-data/using-graphical-client.md
          - Object Storage for Archiving Data: hpc-environment-basics/linux-usage/working-with-data/copying-data/object-storage-archiving-data.md
      - Genders and PDSH: hpc-environment-basics/linux-usage/genders-pdsh.md
  - Flight Environment:
    - flight-environment/index.md
  - Flight Solo:
    - flight-solo/index.md
    - Cluster Build Methods:
      - flight-solo/cluster-build-methods/index.md
      - Example Cluster: flight-solo/cluster-build-methods/example-cluster.md
      - Choose Your Own Adventure: flight-solo/cluster-build-methods/modular.md
      - All Methods:
        - SLURM Standalone AWS: flight-solo/cluster-build-methods/slurm-standalone-aws.md
        - SLURM Multinode AWS: flight-solo/cluster-build-methods/slurm-multinode-aws.md
        - SLURM Standalone Azure: flight-solo/cluster-build-methods/slurm-standalone-azure.md
        - SLURM Multinode Azure: flight-solo/cluster-build-methods/slurm-multinode-azure.md
        - Kubernetes Multinode AWS: flight-solo/cluster-build-methods/kubernetes-multinode-aws.md
        - Kubernetes Multinode Azure: flight-solo/cluster-build-methods/kubernetes-multinode-azure.md
        - Jupyter Lab Standalone AWS: flight-solo/cluster-build-methods/jupyter-lab-standalone-aws.md
        - Jupyter Lab Standalone Azure: flight-solo/cluster-build-methods/jupyter-lab-standalone-azure.md
  - HPC Workflows:
    - hpc-workflows/index.md
theme:
  name: material
  logo: assets/images/logo.png
  features:
    - content.code.annotate
    - navigation.sections
    - navigation.indexes # Allows adding overview pages to sections, name them index.md
    - navigation.tabs
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  version:
    provider: mike
    default:
      - latest
      - staging
plugins:
  - macros:
      include_dir: partials
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      title: On this page
