site_name: OpenFlightHPC
site_url: 'https://www.openflighthpc.org/'
repo_url: https://github.com/openflighthpc/docs.openflighthpc.org
nav:
  - Overview:
    - docs/index.md
    - Prerequisites: docs/overview/prerequisites.md
    - Where Can I Get Help: docs/overview/get-help.md
  - HPC Concepts:
    - docs/hpc-concepts/index.md
    - Network and Hardware: docs/hpc-concepts/network-hardware.md
    - Infrastructure: docs/hpc-concepts/infrastructure.md
    - Base System: docs/hpc-concepts/base-system.md
    - User Management: docs/hpc-concepts/user-management.md
    - Storage: docs/hpc-concepts/storage.md
    - Monitoring: docs/hpc-concepts/monitoring.md
    - HPC Environment: docs/hpc-concepts/hpc-environment.md
    - Verification: docs/hpc-concepts/verification.md
  - HPC Environment Basics:
    - docs/hpc-environment-basics/index.md
    - Linux Environment Usage:
      - docs/hpc-environment-basics/linux-usage/index.md
      - CLI Basics:
        - docs/hpc-environment-basics/linux-usage/cli-basics/index.md
        - Logging In: docs/hpc-environment-basics/linux-usage/cli-basics/logging-in.md
        - Understanding the CLI: docs/hpc-environment-basics/linux-usage/cli-basics/understanding-the-cli.md
        - Moving Between Hosts: docs/hpc-environment-basics/linux-usage/cli-basics/moving-between-hosts.md
        - Becoming the Root User: docs/hpc-environment-basics/linux-usage/cli-basics/becoming-root.md
      - Working with Data and Files:
        - docs/hpc-environment-basics/linux-usage/working-with-data/index.md
        - Storage Types: docs/hpc-environment-basics/linux-usage/working-with-data/storage-types.md
        - Your Home Directory: docs/hpc-environment-basics/linux-usage/working-with-data/your-home-directory.md
        - Copying Data Between Hosts: docs/hpc-environment-basics/linux-usage/working-with-data/copy-between-hosts.md
        - Copying Data to a HPC Environment:
          - docs/hpc-environment-basics/linux-usage/working-with-data/copying-data/index.md
          - Using CLI: docs/hpc-environment-basics/linux-usage/working-with-data/copying-data/using-cli.md
          - Using Graphical Client: docs/hpc-environment-basics/linux-usage/working-with-data/copying-data/using-graphical-client.md
          - Object Storage for Archiving Data: docs/hpc-environment-basics/linux-usage/working-with-data/copying-data/object-storage-archiving-data.md
      - Genders and PDSH: docs/hpc-environment-basics/linux-usage/genders-pdsh.md
    - HPC Environment Usage:
      - docs/hpc-environment-basics/hpc-usage/index.md
      - Job Schedulers:
        - docs/hpc-environment-basics/hpc-usage/job-schedulers/index.md
        - Types of Compute Job: docs/hpc-environment-basics/hpc-usage/job-schedulers/jobs.md
      - SLURM:
        - docs/hpc-environment-basics/hpc-usage/slurm/index.md
        - Running Jobs:
          - Interactive Jobs: docs/hpc-environment-basics/hpc-usage/slurm/running-jobs/interactive.md
          - Batch Jobs: docs/hpc-environment-basics/hpc-usage/slurm/running-jobs/batch.md
          - Array Jobs: docs/hpc-environment-basics/hpc-usage/slurm/running-jobs/array.md
          - Providing Job Configuration: docs/hpc-environment-basics/hpc-usage/slurm/running-jobs/job-configuration.md
          - Dynamic Scheduler Variables: docs/hpc-environment-basics/hpc-usage/slurm/running-jobs/dynamic-vars.md
          - Requesting More Resources: docs/hpc-environment-basics/hpc-usage/slurm/running-jobs/requesting-resources.md
        - Using the Scheduler:
          - View and Control Jobs: docs/hpc-environment-basics/hpc-usage/slurm/using-scheduler/view-control.md
          - View Compute Host Status: docs/hpc-environment-basics/hpc-usage/slurm/using-scheduler/host-status.md
          - View Default Resources: docs/hpc-environment-basics/hpc-usage/slurm/using-scheduler/default_resources.md
        - Further Documentation: docs/hpc-environment-basics/hpc-usage/slurm/further-docs.md
  - Flight Environment:
    - docs/flight-environment/index.md
    - Obtaining Flight Environment:
      - docs/flight-environment/get-flight/index.md
      - Installation: docs/flight-environment/get-flight/install.md
      - Configuration: docs/flight-environment/get-flight/configure.md
    - Using Flight Environment:
      - docs/flight-environment/use-flight/index.md
      - Basics: docs/flight-environment/use-flight/environment-basics.md
      - Flight User Suite:
        - docs/flight-environment/use-flight/flight-user-suite/index.md
        - Flight Desktop:
          - docs/flight-environment/use-flight/flight-user-suite/flight-desktop/index.md
          - Prepare a Desktop Type: docs/flight-environment/use-flight/flight-user-suite/flight-desktop/prepare.md
          - Launch a Desktop Session: docs/flight-environment/use-flight/flight-user-suite/flight-desktop/launch.md
          - Port Forwarding a Desktop Session: docs/flight-environment/use-flight/flight-user-suite/flight-desktop/port-forward.md
          - Resize a Desktop Session: docs/flight-environment/use-flight/flight-user-suite/flight-desktop/resize.md
          - Viewing and Terminating Sessions: docs/flight-environment/use-flight/flight-user-suite/flight-desktop/viewing-terminating.md
          - Securing your Desktop Session: docs/flight-environment/use-flight/flight-user-suite/flight-desktop/secure.md
        - Flight Env:
          - docs/flight-environment/use-flight/flight-user-suite/flight-env/index.md
          - Usage: docs/flight-environment/use-flight/flight-user-suite/flight-env/usage.md
          - Package Ecosystems:
            - docs/flight-environment/use-flight/flight-user-suite/flight-env/ecosystems/index.md
            - Conda: docs/flight-environment/use-flight/flight-user-suite/flight-env/ecosystems/conda.md
            - Easybuild: docs/flight-environment/use-flight/flight-user-suite/flight-env/ecosystems/easybuild.md
            - Modules: docs/flight-environment/use-flight/flight-user-suite/flight-env/ecosystems/modules.md
            - Singularity: docs/flight-environment/use-flight/flight-user-suite/flight-env/ecosystems/singularity.md
            - Spack: docs/flight-environment/use-flight/flight-user-suite/flight-env/ecosystems/spack.md
        - Flight Silo:
          - docs/flight-environment/use-flight/flight-user-suite/flight-silo/index.md
          - Silos: docs/flight-environment/use-flight/flight-user-suite/flight-silo/silos.md
          - Files: docs/flight-environment/use-flight/flight-user-suite/flight-silo/files.md
          - Software: docs/flight-environment/use-flight/flight-user-suite/flight-silo/software.md
          - Migrations: docs/flight-environment/use-flight/flight-user-suite/flight-silo/migrations.md
      - Flight Web Suite:
        - docs/flight-environment/use-flight/flight-web-suite/index.md
        - Setup: docs/flight-environment/use-flight/flight-web-suite/setup.md
        - Landing Page: docs/flight-environment/use-flight/flight-web-suite/landing-page.md
        - Console: docs/flight-environment/use-flight/flight-web-suite/console.md
        - Desktop: docs/flight-environment/use-flight/flight-web-suite/desktop.md
        - File Manager: docs/flight-environment/use-flight/flight-web-suite/file-manager.md
      - Flight Admin Tools:
        - docs/flight-environment/use-flight/flight-admin-tools/index.md
        - Flight Gather: docs/flight-environment/use-flight/flight-admin-tools/gather.md
        - Flight Hunter: docs/flight-environment/use-flight/flight-admin-tools/hunter.md
        - Flight Profile: docs/flight-environment/use-flight/flight-admin-tools/profile.md
        - Flight PDSH: docs/flight-environment/use-flight/flight-admin-tools/pdsh.md
  - Flight Solo:
    - docs/flight-solo/index.md
    - Getting Started: docs/flight-solo/quickstart-guide.md
    - Understanding Flight Solo:
      - docs/flight-solo/understand-solo/index.md
      - User Data: docs/flight-solo/understand-solo/user-data.md
    - Getting Flight Solo:
      - docs/flight-solo/get-solo/index.md
      - Import to AWS: docs/flight-solo/get-solo/aws.md
      - Import to Azure: docs/flight-solo/get-solo/azure.md
      - Import to OpenStack: docs/flight-solo/get-solo/openstack.md
      - Import to Concertim Cloud: docs/flight-solo/get-solo/concertim-cloud.md
    - Cluster Build Methods:
      - docs/flight-solo/cluster-build-methods/index.md
      - Choose Your Own Adventure: docs/flight-solo/cluster-build-methods/modular.md
      - Workflows:
        - docs/flight-solo/cluster-build-methods/workflows/index.md
        - Kubernetes on AWS with Auto-Applying: docs/flight-solo/cluster-build-methods/workflows/kubernetes-aws-auto-apply.md
        - SLURM Standalone on OpenStack with Auto-Configure: docs/flight-solo/cluster-build-methods/workflows/slurm-openstack-autoconfig.md
      - General Methods:
        - SLURM Standalone:
          - AWS: docs/flight-solo/cluster-build-methods/slurm-standalone-aws.md
          - Azure: docs/flight-solo/cluster-build-methods/slurm-standalone-azure.md
          - OpenStack: docs/flight-solo/cluster-build-methods/slurm-standalone-openstack.md
          - Concertim Cloud: docs/flight-solo/cluster-build-methods/slurm-standalone-concertim-cloud.md
        - SLURM Multinode:
          - AWS: docs/flight-solo/cluster-build-methods/slurm-multinode-aws.md
          - Azure: docs/flight-solo/cluster-build-methods/slurm-multinode-azure.md
          - OpenStack: docs/flight-solo/cluster-build-methods/slurm-multinode-openstack.md
          - Concertim Cloud: docs/flight-solo/cluster-build-methods/slurm-multinode-concertim-cloud.md
        - Kubernetes: 
          - AWS: docs/flight-solo/cluster-build-methods/kubernetes-multinode-aws.md
          - Azure: docs/flight-solo/cluster-build-methods/kubernetes-multinode-azure.md
          - OpenStack: docs/flight-solo/cluster-build-methods/kubernetes-multinode-openstack.md
          - Concertim Cloud: docs/flight-solo/cluster-build-methods/kubernetes-multinode-concertim-cloud.md
        - Jupyter Lab:
          - AWS: docs/flight-solo/cluster-build-methods/jupyter-lab-standalone-aws.md
          - Azure: docs/flight-solo/cluster-build-methods/jupyter-lab-standalone-azure.md
          - OpenStack: docs/flight-solo/cluster-build-methods/jupyter-lab-standalone-openstack.md
          - Concertim Cloud: docs/flight-solo/cluster-build-methods/jupyter-lab-standalone-concertim-cloud.md
    - Admin Guides:
      - Concertim Cloud: 
        - docs/flight-solo/admin-guides/concertim-cloud/index.md
        - SLURM Multinode:
          - docs/flight-solo/admin-guides/concertim-cloud/slurm-multinode/index.md
          - Launch Core Infrastructure: docs/flight-solo/admin-guides/concertim-cloud/slurm-multinode/launch-core-infra.md
          - Add Storage Server: docs/flight-solo/admin-guides/concertim-cloud/slurm-multinode/add-storage.md
          - Add, Remove & Resize Nodes: docs/flight-solo/admin-guides/concertim-cloud/slurm-multinode/manage-nodes.md
          - Managing SLURM Queues: docs/flight-solo/admin-guides/concertim-cloud/slurm-multinode/manage-slurm.md
          - Managing Users: docs/flight-solo/admin-guides/concertim-cloud/slurm-multinode/manage-users.md
          - Working with GPUs: docs/flight-solo/admin-guides/concertim-cloud/slurm-multinode/gpu-nodes.md
  - HPC Workflows:
    - docs/hpc-workflows/index.md
    - Benchmarking:
      - HPL: docs/hpc-workflows/hpl.md
      - IMB: docs/hpc-workflows/imb.md
    - HPC Applications:
      - Bowtie: docs/hpc-workflows/bowtie.md
      - Hadoop: docs/hpc-workflows/hadoop.md
      - OpenFoam:
        - docs/hpc-workflows/openfoam/index.md
        - Install OpenFOAM: docs/hpc-workflows/openfoam/install.md
        - MPI Workflow: docs/hpc-workflows/openfoam/mpi.md
        - Simple Workflow: docs/hpc-workflows/openfoam/simple.md
      - Tensorflow: docs/hpc-workflows/tensorflow.md
  - Greener HPC:
    - docs/greener-hpc/index.md
not_in_nav: |
  /index.md
  /solo/index.md
  /warehouse
theme:
  name: material
  custom_dir: custom_theme/
  logo: assets/images/openflighthpc_white.svg
  favicon: assets/images/bumcloud.svg
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.sections
    - navigation.indexes # Allows adding overview pages to sections, name them index.md
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
extra:
  version:
    provider: mike
    default: latest
plugins:
  - macros:
      include_dir: partials
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - spellcheck:
      backends:
        - symspellpy
        - codespell:  # or nested configs
            dictionaries: [clear, rare, informal, usage, code, names]
      known_words: codespell/known_words.txt
      ignore_code: yes
      min_length: 3
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - custom_theme/.icons
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      title: On this page
extra_css: 
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/warehouse.js
