heat_template_version: 2021-04-16
parameters:
  clustername:
    type: string
    label: Cluster Name
    description: The name to give the cluster

  solo-image:
    type: string
    label: Flight Solo Image ID
    default: 'Flight Solo 2024.1'

  node-number:
    type: string
    label: Number of node
resources:
  node-pad:
    type: OS::Heat::Value
    properties:
      type: string
      value:
        yaql:
          expression: concat(str(int(int($.data.padding) - int(len(str($.data.num)))) * "0"), str($.data.num))
          data:
            num: { get_param: node-number }
            padding: 3

  node-pri-port:
    type: OS::Neutron::Port
    properties:
      name: { list_join: ['-', ['node', { get_attr: [ node-pad, value ] }, 'pri', { get_param: clustername }]] }
      network: { list_join: ['-', [{ get_param: clustername }, 'network']] }
      security_groups:
        - { list_join: ['-', [{ get_param: clustername }, 'network-pri-sg']] }
      fixed_ips:
        - subnet: { list_join: ['-', [{ get_param: clustername }, 'network-pri' ]] }
          ip_address: { list_join: ['.', [ '10.100.1', { get_param: node-number } ]] }

  node:
    type: OS::Nova::Server
    properties:
      name: { list_join: ['.', [ { list_join: [ '', ['node', {get_attr: [node-pad, value]} ]]}, { get_param: clustername }, 'alces.network']] }
      flavor: c1.large
      admin_user: flight
      networks:
          - port: { get_resource: node-pri-port }
      block_device_mapping_v2:
        - volume_id: { get_resource: node-vol }
          boot_index: 0
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            fqdn: node$pad.$clustername.alces.network
            write_files:
              - content: |
                  SERVER=$gateway-pri-ip
                  LABEL=node$pad
                path: /opt/flight/cloudinit.in
                permissions: '0600'
                owner: root:root
          params:
            $clustername: { get_param: clustername }
            $gateway-pri-ip: '10.100.0.101'
            $pad: { get_attr: [ node-pad, value ] }

  node-vol:
    type: OS::Cinder::Volume
    properties:
      name: { list_join: ['-', ['node', { get_attr: [ node-pad, value ] }, { get_param: clustername }, 'disk']] }
      image: { get_param: solo-image }
      size: 16
